# Uncomment this line to define a global platform for your project
platform :ios, '10.0'
use_frameworks!

target 'CarenetSDK-Test' do
 
  pod 'CarenetSDK', :podspec => '../CarenetSDK.podspec'
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'HockeySDK'

end
